### PR TITLE
Implement focusing last active window on click

### PR DESCRIPTION
**Pull request by francislavoie**
Relevant launchpad bug report: https://bugs.launchpad.net/plank/+bug/1083359

I've wanted this functionality for a long time. Not sure if there's any bugs in my implementation, I tried to cover the cases I could think of, but I'm sure I missed some stuff. I don't use workspaces, for example, so I probably didn't hit those cases correctly.

I also probably want to set the last active when focusing on a specific window via the right-click submenu, or when they get alt-tabbed to. Didn't dig to figure out how to do this yet. Would appreciate some help on this front!

This is partially incomplete I'd say, because it just replaces `smart_focus` with my own implementation. I think the ideal thing if this was to be merged is to add a configuration option to switch between the `smart_focus` mode and my newly created `last_active_focus` mode.

In broad strokes, what this does:
- Tracks a list of an app's window's XIDs in an ArrayList
- When a window is added/removed, the list is synced
- The goal is to have subsequent clicks on the app icon cycle through all the windows of the app, in order of last active. 
- If no window of the app is focused, it'll bring up the last active window (the one at the top of the list)
- If the currently active window is the one from the same app, it moves the current window to the end of the list and focuses the window at the new front of the list (i.e. the next one)
- If there's only one window for an app, it has the same behaviour as before, i.e. minimize/unminimize toggle
- Clicking the app icon no longer minimizes the entire app if there's more than one window for that app

I tried to mirror as much as I could the behaviour that can be found in Windows that I love. See here for details on how to enable it on Windows (requires a reg edit)
https://www.howtogeek.com/howto/16334/make-the-taskbar-buttons-switch-to-the-last-active-window-in-windows-7/

I've been complaining a bunch on the elementaryOS subreddit for a while now, finally found some time this weekend to try and tackle it properly.

### CODE REVIEW

**Comment by Shnatsel** [comment]
I have prototyped something similar here with a very minimal changeset: https://github.com/Shnatsel/plank/tree/no-more-minimize 
I also have a build of Plank with this patch for Loki in [this PPA](https://launchpad.net/~shnatsel/+archive/ubuntu/personal-patches) to ~ease testing in day-to-day use~ use it myself before it's merged.

We've discussed it with Dan and Cassidy (the UX guys of elementary), here's a summary as far as I remember it:

1. We've been meaning to kill explicit "minimize" action for years, it's OK to finally let it go. It is not the expected action for clicking the dock icon of the active app anyway.
1. Lack of a discoverable way to switch between windows of the same app via the dock is a problem.
1. Switching to the next window of the same app on single click seems reasonable, if there are indeed several windows. We could not agree on the exact order in which the windows should be switched (current scrollwheel behavior vs alt-tab behavior), but either should be acceptable.
1. Minimizing when there is only one window of an app and switching between windows of the app if there are several is a no-go. Having the same user action do different things depending easy-to-miss context is not a good idea.
1. Doing nothing on clicking the active app when it has only one window is also a no-go. See "[Controls that do nothing](https://elementary.io/docs/human-interface-guidelines#controls-that-do-nothing)" in the HIG. There has to be some kind of feedback.
1. Making the window manager, Gala, animate the active window to attract attention to it if there is only one window of an app and cycling through windows of the app if there are several is acceptable behavior for single click on the dock icon of the currently active application.

**Comment by francislavoie** [comment]
I agree with 5, disagree with 4. I think 4 is the best solution to solve 5. After having used that behaviour for years (in Windows), I think that's the best way to go.

**Comment by francislavoie** [comment]
FWIW I've tried that same change you implemented (just `focus_next` instead of minimizing) but I found that it still left a lot of unresolved issues as you pointed out, mainly with ordering and when returning to the same app from a different one (jumps back to the first one in the list IIRC?). That's why I implemented a list of window IDs.

I'm finding that I really need the added part of reordering the list when clicking on a specific window from the right-click menu, but I haven't gotten around to trying to get that in yet. Will try ASAP.

**Comment by Shnatsel** [comment]
I've been meaning to proceed with my implementation but I'm waiting on advice on handling the Plank => WM communication from Plank's maintainer, Rico.

> but I found that it still left a lot of unresolved issues as you pointed out.

Huh? What issues are those? It felt fine to me, although I rarely use more than two windows of the same app so I could have missed something.

**Comment by Shnatsel** [comment]
Oh yeah, and I'm told that making this behavior a configuration option is a requirement to get it merged.

**Comment by francislavoie** [comment]
I use like 10 with Sublime Text, so it's pretty painful when it doesn't go to the window I want (then need to cycle through a bunch of them, etc) when I usually only actively use like two at any given time (in which case I want those two last active ones to be at the top of the list)

And when I launch the app with windows from my last session, they get ordered kinda randomly in Plank's window list so it's weird to deal with getting the window I want.

**Comment by Shnatsel** [comment]
I still don't understand how your implementation is different from simply calling `focus_next` instead of minimizing. The behavior in PR description seems to be exactly what that does.

**Comment by francislavoie** [comment]
1. Open a bunch of windows of the same app (5+)
2. Cycle a few times through the windows of that app
3. Switch to another app
4. Switch back to the original app
5. You usually don't get the same window as you last had, but instead the _next_ window in the list from the last one you had.

Edit: gotta go for now, so might not reply quickly

**Comment by Shnatsel** [comment]
Ah, my branch actually fixes that in a very trivial way. I've simply preserved the "bring up all windows of an app" as click action when the app is not focused, and cycle through windows only when it's focused. Voila.

**Comment by francislavoie** [comment]
I really don't like that. Bringing up all the windows is _never_ the
behaviour I want. I often arrange my windows in a certain way on my screen,
and if all the windows come up then it totally trashes that.

**Comment by Blast-City** [comment]
Anyone knows what is the status on this issue?

One of the issues that i have on elementary is the following:

1- Open two windows of the same app
2- Change The workspace
3- Click the application icon

Result: The workspace is switched to the one that have the application, but the foreground window is not the same that was when you moved to point 2.

The foreground window should be the same.

**Comment by francislavoie** [comment]
I have no plans to continue work on this PR, I'm no longer using ElementaryOS as a daily driver (I'm using Ubuntu now with `pantheon-terminal` which was my favourite component, because at my new job, most people use Ubuntu)

I'll close this now, anyone should feel free to pick this back up if they wish.

**Comment by Sadi58** [comment]
@francislavoie 
BTW I think there's a version issue when using the elementary-os stable ppa channel in addition to official ubuntu repositories: "0.11.4+git20180707....-0elementary0.5.1 (bionic)" is suggested as an upgrade for "0.11.4-2 (bionic)"

**Comment by francislavoie** [comment]
This isn't my repo, I think you're reporting that in the wrong place.

**Comment by Sadi58** [comment]
Sorry, I know this is not the place to report an issue. ;-)
I didn't know that it wasn't your repo.
Thanks.

**Comment by Blast-City** [comment]
> Sorry, I know this is not the place to report an issue. ;-)
> I didn't know that it wasn't your repo.
> Thanks.

Hi.

You're using Juno, right? Could you test if the issue that i talk about on my post above is happening on Juno as well?

Thanks.

**Comment by Sadi58** [comment]
@Blast-City 
I use Linux Mint 19.1 actually, but tested it on live USB HDD including elementary 0.5 and saw that it happens there, too.

**Comment by Blast-City** [comment]
> @Blast-City
> I use Linux Mint 19.1 actually, but tested it on live USB HDD including elementary 0.5 and saw that it happens there, too.

Thanks.

I will open a new issue.

**Pull request closed without merging**
