### PR TITLE
Plank overlaps with windows that reserved workarea space

### PR DESCRIPTION
**Pull request by swissiety**
Plank overlaps with panels although the panel is reserving screen space via workarea.
This happens e.g. when the xfce4-panel is on upper side while plank is on the left side with the fill alignment option selected. 
As a result both overlapping windows are changing its stacking order which is quite annoying.
The modification should fix that.

Note: make sure plank is executed after the panel reserved its workarea space to see a different behavior.

### CODE REVIEW

**Comment by Sadi58** [comment]
As workaround for this issue I insert a space via a special .desktop file that has a transparent icon and opens plank preferences on click. ;-)
Hope this gets merged as soon as possible.

**Comment by emanuelserpa** [comment]
this patch is pretty important to use plank sideways and is sad that more than a year latter nobody answer whats wrong or merge this PR.

**Comment by fossfreedom** [comment]
According to this bug report this patch causes major issues when the monitor changes resolution ... at least to mutter based desktops 

https://bugs.launchpad.net/plank/+bug/1931803

**Comment by g6094199** [comment]
also probably causes:

https://bugs.launchpad.net/bugs/1949741

**Pull request closed without merging**
